### ISSUE TITLE
can we use the arxiv data from kaggle to replase s3 source?

### ISSUE THREAD

**Issue by loveJasmine** [mattbierbaum/arxiv-public-datasets#10]
https://www.kaggle.com/Cornell-University/arxiv

**Comment by colinclement** [comment]
You can follow the Bulk Downloads section of the Kaggle site and try my answer to [this issue](https://github.com/mattbierbaum/arxiv-public-datasets/issues/8) to convert the PDFs provided by Kaggle into textfiles. If you want to then extract the co-citation graph, you'll need to set `$DIR_FULLTEXT` to the location you stored the PDFs/converted text, and then you can simply run `python bin/cocitations.py`. Let me know if this doesn't work for you.

**Comment by colinclement** [comment]
@loveJasmine were you able to get this suggestion working?

**Comment by loveJasmine** [comment]
sorry, I cannot try it recently since the internet from chinA not very stable.

**Comment by colinclement** [comment]
I believe @quynhneo has proposed [a PR](https://github.com/mattbierbaum/arxiv-public-datasets/pull/14) which allows using our tools on the Kaggle data source. Once that PR is merged I will close this issue.

**Comment by quynhneo** [comment]
should be ok now https://github.com/mattbierbaum/arxiv-public-datasets/pull/14

**Comment by colinclement** [comment]
PR #14 merged, resolving this issue.
