### ISSUE TITLE
pdfdownload.py problem

### ISSUE THREAD

**Issue by YupingLu** [mattbierbaum/arxiv-public-datasets#19]
Hi,

I had a problem when running pdfdownload.py. Below is the error. Is there a way to ignore that entry and continue downloading? Thanks.

Traceback (most recent call last):
  File "bin/pdfdownload.py", line 7, in <module>
    s3_bulk_download.download_check_tarfiles(manifest)
  File "/data/arxiv-public-datasets/arxiv_public_data/s3_bulk_download.py", line 194, in download_check_tarfiles
    download_check_tarfile(fileinfo['filename'], fileinfo['md5sum'], dryrun=dryrun)
  File "/data/arxiv-public-datasets/arxiv_public_data/s3_bulk_download.py", line 176, in download_check_tarfile
    raise AssertionError(msg)
AssertionError: MD5 '87f546d3ad4f3e9d19357ea1558b432c' does not match expected '63ac7e9ea4b6896f5e14e766d60b68c7' for file 'pdf/arXiv_pdf_1607_007.tar'

**Comment by quynhneo** [comment]
You could ignore but change changing the line `raise AssertionError(msg)` but why not try to see why is the error happening?

**Comment by YupingLu** [comment]
Thanks @quynhneo . It turns to be my AWS credential issue which is only valid for 12 hours. The problem can be solved by updating the credential.

**Comment by colinclement** [comment]
Thanks for the suggestion @quynhneo. @YupingLu it sounds like your issue is resolved so I will close it. Feel free to add remarks if this is not the case.
