### ISSUE TITLE
Conversion from PDF to json

### ISSUE THREAD

**Issue by yananchen1989** [mattbierbaum/arxiv-public-datasets#21]
Hi, is there a method in this repo to convert PDFs into json data, which consists of author list, published date, abstract and content etc ?

I see that `convert_safe` and `convert` function only convert PDF into texts, which are not as organized as json format.

(I use `gsutil` to cp PDFs from GCP storage and I tend to convert them into json data, which will further be transformed into tabular data).

Thanks in advance.

**Comment by colinclement** [comment]
You can get the author list, title, submission date, and (hashed) abstracts from the metadata in the [release page](https://github.com/mattbierbaum/arxiv-public-datasets/releases/tag/v0.2.0). I recommend re-running our metadata collection tool to get the abstracts as well, which takes about a day or so. Extracting data from the PDFs is very noisy, so I would only rely on the PDFs for the paper content. An alternative is to download the LaTeX source files and parse those for the content, but the metadata is still the only source of the submission dates.

**Comment by colinclement** [comment]
@yananchen1989 I will close this issue, feel free to re-open it if your issue is not resolved
