### ISSUE TITLE
Original tex file

### ISSUE THREAD

**Issue by chaodreaming** [mattbierbaum/arxiv-public-datasets#23]
I don't want a pdf file because there is no way to extract the content well from a pdf file, I want to get a tex file, there are many people who provide that type of file and I want to extract the formulas from the tex file to make a bigger data set

**Comment by colinclement** [comment]
You can use the tool to download the raw tex. You can see we have the tex manifest path hardcoded [here](https://github.com/mattbierbaum/arxiv-public-datasets/blob/821d543e9ed9d04426e8a76d471cd94ed92ff994/arxiv_public_data/s3_bulk_download.py#L62). You need only clone the repo, replace the reference to `S3_PDF_MANIFEST` [here](https://github.com/mattbierbaum/arxiv-public-datasets/blob/821d543e9ed9d04426e8a76d471cd94ed92ff994/arxiv_public_data/s3_bulk_download.py#L135) with the tex manifest path, and run the `pdfdownload.py` script which with this modification will download the tex source instead. Of course, the other tools we provide for using OCR on the fulltext will not work and will be unnecessary in any case. Good luck!

**Comment by rmovva** [comment]
Is it possible to download the TeX files without paying for AWS -- for example, does Kaggle host the TeX files somewhere?

**Comment by colinclement** [comment]
Kaggle only currently allows free downloading of the PDFS, see [this section of the README](https://github.com/mattbierbaum/arxiv-public-datasets#kaggle-hosting-arxiv-data).
