### ISSUE TITLE
download_and_process.py

### ISSUE THREAD

**Issue by samstanwyck** [mattbierbaum/arxiv-public-datasets#3]
Thanks for the resource! Dumb question - in the comments for s3_bulk_download.py you suggest running s3.download_and_process(manifest). I don't see this function - am I missing something?

**Comment by colinclement** [comment]
Thanks for your interest! Yeah, that module docstring is out of date--I would just follow the README to download and process the PDfs. If you're interested in running that function directly, I believe we changed the name to `process_manifest_files`, which takes a list of files from the manifest, downloads each one, and converts the PDFs in each one into rawtext. If you just want to download the tarfiles without running the pdftotext conversion, you can use `download_check_tarfile`, where you can provide the filename and the md5 of the contents as provided by the manifest.
