### ISSUE TITLE
download only a section of arxiv

### ISSUE THREAD

**Issue by lfoppiano** [mattbierbaum/arxiv-public-datasets#5]
Hi, 
   I'm wondering whether it would be possible to download only a sub-section of the arxiv archive. For example, I'm interested only in the condensed matter category (`cond-mat`) https://arxiv.org/archive/cond-mat 

Is there a way to do that?

**Comment by colinclement** [comment]
You can preview the contents by downloading and examining the manifest (after following the authentication setup):
```python
from arxiv_public_data import s3_bulk_download
manifest = s3_bulk_download.get_manifest()
```
you can examine the values of each key: the keys are the AWS tarpdf dumps and the values are the arXiv IDs of each paper, e.g. `0001/cond-mat0001460.pdf` is an element of `manifest['pdf/arXiv_pdf_0001_001.tar']`.

I believe it's [organized by months](https://arxiv.org/help/arxiv_identifier), e.g. `pdf/arXiv_pdf_0001_001.tar` is the first batch of year 2000 month 01 (January 2000). So you can try to focus your attention by only grabbing a subset of the `tar` files in the manifest by examining and filtering their content arXiv IDs. I just calculated that 221/2261 of the manifest files contain arxivIDs with 'cond-mat', so you could just download those at the cost of probably $10 or so.

To do so, select only the subset of the manifest you care about, perhaps
```python
subset_manifest = {}
for tarpdf, files in manifest.items():
    for fil in files:
        if 'cond-mat' in fil:
            subset_manifest[tarpdf] = files
            break
```
and then hand this trimmed manifest to the download function:
```python
s3_bulk_download.download_check_tarfiles(subset_manifest)
```
and the results will be saved as indicated in the README.

If you want to use the rest of our pipeline to analyze only this subset and extract the co-citation graph, fulltext, etc, you'll need to modify the command line scripts in `bin/` by explicitly passing in your customized manifest, or by replacing the default manifest file in `$DIR_PDFTARS/arxiv-manifest.xml.gz` with your customized manifest.

**Comment by lfoppiano** [comment]
@colinclement  Thank you for your quick answer! I will try and let you know

**Comment by colinclement** [comment]
No problem, please close the issue when you are satisfied.

**Comment by lfoppiano** [comment]
@colinclement I've given a try, I modified the `pdfdownlod.py` which seemed to be the simplest approach. 

I have few more questions. 

The manifest looks like this: 
```
  <file>
    <content_md5sum>07234b3a03a15391c5cf7ce4905c136f</content_md5sum>
    <filename>pdf/arXiv_pdf_0001_001.tar</filename>
    <first_item>astro-ph0001001</first_item>
    <last_item>math0001014</last_item>
    <md5sum>16857799a6b343586691b56eace826fb</md5sum>
    <num_items>1797</num_items>
    <seq_num>1</seq_num>
    <size>524304163</size>
    <timestamp>2019-05-22 03:20:55</timestamp>
    <yymm>0001</yymm>
  </file>
```

so it's a list of dicts, I've modifed the code to iterate over each meatadata: 

```
    for manifest in manifests:
        for tarpdf, files in manifest.items():
            for fil in files:
                if 'cond-mat' in fil:
                    subset_manifest[tarpdf] = files
                    break

```

But then I realised that `for tarpdf, files in manifest.items():` doesn't seems to be right for this manifest. Are you sure I don't have to download all the tar files? Or maybe I've done something wrong? 

I've also download the oai manifest: `arxiv-metadata-oai-2020-08-03.json.gz` which looks more complete. Isn't this supposed to be used instead of downloading another metadata file from s3?

**Comment by bluetyson** [comment]
Does similar hold for different  arxivs, e.g, earthArxiv, bioArxiv etc.?

**Comment by colinclement** [comment]
@lfoppiano That's my bad, I haven't looked at this code in a year! You're right about the manifest, I was confused with another file our pipeline creates called `manifest-index.json` which is what I used as the manifest file. You will not be able to use the S3 manifest as I described above. I updated [the latest release](https://github.com/mattbierbaum/arxiv-public-datasets/releases/tag/v0.2.0) to include this `manifest-index.json` (decorated with the released version and date). Go ahead and download that, replacing its contents in the `manifest` object in my solution above. 

There is also a new [collaboration between Cornell University and Kaggle](https://www.kaggle.com/Cornell-University/arxiv) to host the arXiv PDF data for free if I'm not mistaken (using our tool I believe), in case you'd be interested in downloading everything for free.

@bluetyson This tool only works for the original arXiv, we have not examined any of the APIs or endpoints of other pre-print services. We would be open to pull requests expanding our tools if they follow similar patterns. I think it's likely the other pre-print services have OAI endpoints which are very similar, so the metadata is likely accessible via our tool in a modified form.

**Comment by bluetyson** [comment]
Thanks Colin

**Comment by bluetyson** [comment]
There is actually an eartArxiv github for an API that downloads files and abstracts - so be a matter of tying into your full text processing as such? e.g. borrow this as such, run it over a directory?

**Comment by colinclement** [comment]
That's certainly possible. Right now our code is tailored to the filename patterns and the arXiv `tarpdf` dump structure, and our co-citation graph processor depends on the arXiv ID format, so it could require some modification to adapt it if earthArxiv has its own conventions. If you have a directory full of `pdf` files you can use [this function](https://github.com/mattbierbaum/arxiv-public-datasets/blob/f0b8a4fd17e7aeed38465ec00a63eb219fe1672e/arxiv_public_data/fulltext.py#L226): it just creates a fulltext file from each `pdf` in the provided directory (there is also a parallel implementation). The fulltext conversion is not very high quality, but is certainly good enough to get good classification results and find co-citations by searching for arXiv IDs. To get the co-citation graph for earthArxiv you'd need to modify the methods in [this file](https://github.com/mattbierbaum/arxiv-public-datasets/blob/master/arxiv_public_data/internal_citations.py) to use the earthArxiv ID format instead of arXiv ID.

**Comment by bluetyson** [comment]
Thanks very much Colin.
